/** Canonical names used by every one-shot CLI command registration. */
export const CLI_COMMANDS = Object.freeze({
  analyze: "analyze",
  inspect: "inspect",
  decompile: "decompile",
  setup: "setup",
  doctor: "doctor",
  uninstall: "uninstall",
  upgrade: "upgrade",
  xrefs: "xrefs",
  trace: "trace",
  capabilities: "capabilities",
  providers: "providers",
  function: "function",
  search: "search",
  importReferenceSource: "import-reference-source",
  inventoryArtifact: "inventory-artifact",
  extractArtifact: "extract-artifact",
  inspectManagedArtifact: "inspect-managed-artifact",
  inspectManagedMembers: "inspect-managed-members",
  compareManagedMembers: "compare-managed-members",
  inspectMacho: "inspect-macho",
  inspectSignature: "inspect-signature",
  listArchitectures: "list-architectures",
  inspectPlist: "inspect-plist",
  demangleSwift: "demangle-swift",
  evidenceImport: "evidence-import",
  evidenceExport: "evidence-export",
  compare: "compare",
  investigateVersions: "investigate-versions",
  captureProcess: "capture-process",
  compareProcessCaptures: "compare-process-captures",
  policy: "policy",
  listBrowserTargets: "list-browser-targets",
  inspectWebPage: "inspect-web-page",
  analyzeWebBundle: "analyze-web-bundle",
  observeWebSession: "observe-web-session",
  discoverWebMcpTools: "discover-webmcp-tools",
  compareWebCaptures: "compare-web-captures",
  captureWebScreenshot: "capture-web-screenshot",
  compareWebScreenshots: "compare-web-screenshots",
  listElectronTargets: "list-electron-targets",
  inspectElectronPage: "inspect-electron-page",
  analyzeJavaScriptApplication: "analyze-javascript-application",
  reconcileJavaScriptRuntime: "reconcile-javascript-runtime",
  traceApplicationFeature: "trace-application-feature",
  compareApplicationVersions: "compare-application-versions",
  runControlledReplay: "run-controlled-replay",
});

/** Ordered primary CLI inventory; aliases are intentionally excluded. */
export const CLI_COMMAND_NAMES = Object.freeze(Object.values(CLI_COMMANDS));
